### ISSUE TITLE
GRM - Grocery and Recipe Manager

### ISSUE THREAD

**Issue by Pakizah** [IEEEmadC/Apps-2017#12]
Team Name : Three Musketeers
Github Link: https://github.com/Pakizah/GRM 
Link to Admin Panel: http://grm-1.apphb.com/
[readme.txt](https://github.com/IEEEmadC/Apps-2017/files/1146347/readme.txt)

**Comment by SangramChavan** [comment]
Some files are pending please refer to the last submission.

**Comment by Pakizah** [comment]
I have already updated repository,Now what's next?

**Comment by Pakizah** [comment]
Please Guide @SangramChavan

**Comment by SangramChavan** [comment]
@Pakizah Any suitable licence!
That's all :+1:

**Comment by Pakizah** [comment]
Done @SangramChavan
