### ISSUE TITLE
Team Trinity

### ISSUE THREAD

**Issue by Nishargo** [IEEEmadC/Apps-2017#13]
Author: Nishargo Nigar, Anannya Banerjee, Nasrin Siddiqua
Country: Bangladesh
Repo: https://github.com/Nishargo/GuideUs

**Comment by SangramChavan** [comment]
Incomplete submittion

**Comment by Nishargo** [comment]
What else is needed?

**Comment by SangramChavan** [comment]
Will check and revert soon.

**Comment by Nishargo** [comment]
I don't see our name in the list. I also completed the stage 2.

**Comment by SangramChavan** [comment]
List will be updated soon.
