### ISSUE TITLE
Team: Hodor

### ISSUE THREAD

**Issue by KananVyas** [IEEEmadC/Apps-2017#14]
author:- Kanan Vyas, Harsh Patel
country:- India
Repo link:- https://github.com/KananVyas/ColdBox

**Comment by SangramChavan** [comment]
Incomplete submission have a look at last submission for reference.

**Comment by KananVyas** [comment]
Now everything is done. Have a look.

**Comment by SangramChavan** [comment]
Cool !! Looks nice now :+1:

**Comment by SangramChavan** [comment]
Licence pending !

**Comment by harsh2011** [comment]
Now licence is add. Have a look.

**Comment by SangramChavan** [comment]
Noted.
