### ISSUE TITLE
PhotoWrote

### ISSUE THREAD

**Issue by Amirh-ranjbar** [IEEEmadC/Apps-2017#19]
Team name: Shadower
members  :  Amirhossein ranjbar
From : Iran, Isfahan , Isfahan Univ of Tech
platform : Android

![photowrote_3](https://user-images.githubusercontent.com/19997963/28239489-77b82e86-6982-11e7-8682-f6f16acb21ca.jpg)

![photowrote_2](https://user-images.githubusercontent.com/19997963/28237831-0982e124-695d-11e7-8d7c-32cd6893d996.jpg)

![photowrote_1](https://user-images.githubusercontent.com/19997963/28237830-06370266-695d-11e7-963e-c48d8081ff13.jpg)

My Idea is about to write information on pictures without destroying the original  picture .

By this App you can easily open a photo in editor and add notes with subject and specific color to the picture

when your return to picture and open it again you have the last notes on it and can view them
 i hope find a way to put information like the same way i do in the PhotoWorote and send it to another guy to watch them in the feature 

For more information contact: Amirh.ranjbar@gmail.com  OR  A.ranjbar.ENG@ieee.org

see Demo on Youtube : https://youtu.be/-_7mJ4G8RKo

[![youtube](https://user-images.githubusercontent.com/19997963/28237888-ea59ab2e-695d-11e7-818b-63aab8354f7a.jpg)](https://youtu.be/-_7mJ4G8RKo)'

see source on github : [github.com/Amirh-ranjbar/PhotoWrote_final_VC](https://github.com/Amirh-ranjbar/PhotoWrote_final_VC)

download APK from google drive :  https://drive.google.com/open?id=0B3kZepVIgOIxQUN0ajdlcEVFR2M

**Comment by SangramChavan** [comment]
Thank you ! Will check and revert soon if anything is missing.
