### ISSUE TITLE
MeEnsina

### ISSUE THREAD

**Issue by joalisson** [IEEEmadC/Apps-2017#22]
Team Name: MeEnsina
Team Members: Joálisson Andrade, Alan Atta and Lucas Almeida
Repository: https://github.com/joalisson/meensina

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by joalisson** [comment]
Ok. Thanks!

**Comment by SangramChavan** [comment]
Nice concept and well submitted :+1:

**Comment by SangramChavan** [comment]
You may apply fo FbStart
FbStart is a program from Facebook designed to help early stage mobile startups build and grow their apps
https://developers.facebook.com/fbstart

**Comment by joalisson** [comment]
@SangramChavan Thanks! We got this package from FBStart.
