### ISSUE TITLE
My diagnostic

### ISSUE THREAD

**Issue by Tonysmarv** [IEEEmadC/Apps-2017#24]
Application Name: My diagnostic
Team Name: Dev4u
Team Members: Jonathan Giovanny Hernandez / Marvin Antonio Mendez
Repository: https://github.com/Tonysmarv/My_diagnostic

**Comment by Tonysmarv** [comment]
Hi, All in order with my project?

**Comment by SangramChavan** [comment]
Yes :+1:  nice work !

**Comment by Tonysmarv** [comment]
thanks,what is the next step?

**Comment by SangramChavan** [comment]
For now its all what we need. 
http://ieeemadc.org/my-diagnostic/

**Comment by Tonysmarv** [comment]
Thanks so much.=)
