### ISSUE TITLE
IIUC_madResearchers

### ISSUE THREAD

**Issue by absak** [IEEEmadC/Apps-2017#25]
https://github.com/absak/ResearchHero

**Comment by SangramChavan** [comment]
Can you point me to the app file eg. apk ?

**Comment by absak** [comment]
@SangramChavan, the apk file link from the repo?

**Comment by absak** [comment]
Here is the apk file link. Sorry, i forgot to delete .gitignore, thats why the apk was not committed at first. 
https://github.com/absak/ResearchHero/tree/master/app/build/outputs/apk

**Comment by SangramChavan** [comment]
Thank you for the update !
