### ISSUE TITLE
Volunteers

### ISSUE THREAD

**Issue by amrithm98** [IEEEmadC/Apps-2017#26]
Volunteers is an android application that allows volunteers in organizing events inside and outside the IEEE Community. The application helps volunteers to coordinate events efficiently in a unified platform.
Team Name : RedTeddy 
Android Repository : https://github.com/amrithm98/Volunteer
Nodejs Backend Repository: https://github.com/amrithm98/Volunteers-Backend

**Comment by SangramChavan** [comment]
Files missing...
Licence and STAGE 2 submission remaining after which your app will be featured on IEEEmadC.org/blog
