### ISSUE TITLE
MediQ

### ISSUE THREAD

**Issue by wasuradananjith** [IEEEmadC/Apps-2017#29]
**Team Name** - TryCatch

**Team Details**

- Wasura Wattearachchi (wasuradananjith@gmail.com)

- Hisan Hunais (hisan.live@gmail.com)

- Kasun Dissanayake (kasunprageethdissanayake@gmail.com)

**GitHub Link**
https://github.com/wasuradananjith/MediQ-V2.git

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.
--
