### ISSUE TITLE
AllForOne

### ISSUE THREAD

**Issue by LarrissaDantas** [IEEEmadC/Apps-2017#31]
https://github.com/GirlPowerIEEE/AllForOne

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by SangramChavan** [comment]
Please add some licence.

**Comment by LarrissaDantas** [comment]
I sent in the second step of submission. The license will be MIT, we put as
an option. Do you have to also put it in the GIT repository? If you have to
put it in the GIT repository, can we still upgrade?

2017-07-19 11:15 GMT-03:00 Sangram Chavan <notifications@github.com>:

**Comment by LarrissaDantas** [comment]
Okay, I put the license in the repository. I hope everything is alright.

2017-07-19 18:25 GMT-03:00 larrissa dantas <larrissadxavier@gmail.com>:

**Comment by SangramChavan** [comment]
Thank you for the quick response :+1:

**Comment by LarrissaDantas** [comment]
Is everything okay with the project?What is missing?



2017-07-24 3:36 GMT-03:00 Sangram Chavan <notifications@github.com>:

**Comment by SangramChavan** [comment]
Everything Ok :+1:
