### ISSUE TITLE
SOS - The Healthcare Companion

### ISSUE THREAD

**Issue by adithya321** [IEEEmadC/Apps-2017#34]
Team Name: **Team SOS**
Team Members: Adithya J, Aditya Manoharan, Vishwanath Jeyaraman
University: SSN College of Engineering, Chennai
Region: India, Asia

[Github Repository](https://github.com/adithya321/SOS-The-Healthcare-Companion)
[APK file](https://github.com/adithya321/SOS-The-Healthcare-Companion/blob/master/app-release.apk)
[YouTube Demo](https://youtu.be/EDdsUSuxibc)

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.
