### ISSUE TITLE
Sohoj Vromon

### ISSUE THREAD

**Issue by N4f33z** [IEEEmadC/Apps-2017#36]
Team Name: RsquareN
Application Name: Sohoj Vromon
Team Member: Runa laila, Nafeez Zawad Hossain, Rahman, Md.Hafijur

We want to make the bus transportation of the certain city. But the transportation system can be quite chaotic. With loads of buses and transports around, those who are new in this city and are not familiar with these routes, will get confused right away. There are various routes for the buses. So, they ask people for the exact bus to reach their destination.Our app is basically a transport related app.Travellers can get information from this app like which one has still got tickets for travelling from the city. Now with this app we will try to provide with the information of various Bus Services,train also and their routes and make things easier for people.

Repository: https://github.com/RsquareN/Sohoj-Vromon

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by SangramChavan** [comment]
We recommend you include some licence which you prefer

**Comment by N4f33z** [comment]
The license has been added.
