### ISSUE TITLE
Lost & Survive 

### ISSUE THREAD

**Issue by Utshaw** [IEEEmadC/Apps-2017#40]
# Lost & Survive
# Team: Buet_Matrix

![poster](https://user-images.githubusercontent.com/18516336/28241679-e0c6d98a-69ba-11e7-966b-357cccdad4f0.png)

## Description 
This Application is for everybody who loves to travel anywhere  in this planet . Even if the traveler is in the desert , mountain , island , jungle or in foreign land this app is ready to help him in a lot of ways . 

![screenshot_20170715-235504](https://user-images.githubusercontent.com/18516336/28241684-fc65e9d8-69ba-11e7-9da8-107a178a1bcc.jpg)

 
## Features 
This app helps the travelers by giving them particular advices for taking precautionary measures before going to certain places . 

![screenshot_20170715-235512](https://user-images.githubusercontent.com/18516336/28241687-09e722ca-69bb-11e7-9647-aaa96f86a8a6.jpg)

If the traveler gets lost in somewhere this app helps him by providing enough advices about surviving in that particular location . 

Surviving in night at inhabitable places is very difficult as there is scarcity of light . This app features torch light functionality which uses the flash of the camera . 
Wherever we get lost we need to know about directions . This app features compass that uses magnetic sensor of the device. 

![4184266633435549392-account_id 1](https://user-images.githubusercontent.com/18516336/28241717-7c68c952-69bb-11e7-88b1-27938977650d.jpg)

Knowing current location is the most important thing when somebody is lost . The user can know his/her current location ( latitude, longitude)  using only GPS(without internet connection) if four (4) GPS satellite are available at that area. 

![screenshot_20170715-235520](https://user-images.githubusercontent.com/18516336/28241711-483583e6-69bb-11e7-8e5a-e31312fd92eb.jpg)

When internet services is available (i.e. at foreign countries) this app helps the users to know about nearest hospitals , police stations .Moreover , this app has a built-in E-mail functionality that uses Gmail API for sending SOS mails. 

![screenshot_20170715-235545](https://user-images.githubusercontent.com/18516336/28241713-693ed7e0-69bb-11e7-9f88-820f8e558769.jpg)

![screenshot_20170715-235551](https://user-images.githubusercontent.com/18516336/28241715-7012c4f0-69bb-11e7-88da-1ace92d6fb80.jpg)

 
# Authors: 
Member Name 1: Farhan Tanvir Utshaw 
E-mail: farhan.tanvir.utshaw@gmail.com 
Member Name 2: Waqar Hassan Khan 
E-mail: waqar.hassan866@gmail.com 
Member Name 3: Ahmed Nafis Fuad  
E-mail: 1505113.anf@ugrad.cse.buet.ac.bd

**Comment by SangramChavan** [comment]
:+1: 
Will check and revert if anything is missing.
