### ISSUE TITLE
Dentogram

### ISSUE THREAD

**Issue by parinishah** [IEEEmadC/Apps-2017#41]
Team Name: Froyo

Repository Link: https://github.com/parinishah/Dentogram

Short Description: An app made with surgical precision, specifically for  the doctors to add their patients along with maintaining a record of their health and prescribing medicines.

License: Apache 2.0

University: School of Engineering and Applied Sciences, Ahmedabad University

Locality: Ahmedabad

Region: India

Authors: Parini Shah, Krish Shah, Suchit Sanghvi

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by parinishah** [comment]
Thank you.

Regards
Team Froyo
