### ISSUE TITLE
BookED

### ISSUE THREAD

**Issue by prabhavgupta** [IEEEmadC/Apps-2017#42]
Team Name : Pikachu
Repo Link : https://github.com/prabhavgupta/Final

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by prabhavgupta** [comment]
Team Name : Pikachu
Repo : https://github.com/prabhavgupta/BookED
It includes 
1. Source Code
2. Screenshots
3. Logo 
4. Feature Graphic
5. YouTube Link

**Comment by SangramChavan** [comment]
Adding some licence would make feel complete !

**Comment by prabhavgupta** [comment]
MIT license has already been added.

**Comment by SangramChavan** [comment]
Thank you !!

**Comment by prabhavgupta** [comment]
You have forked the wrong project. Please use this Repo : https://github.com/prabhavgupta/BookED

**Comment by prabhavgupta** [comment]
It will be great if you can Update your forked Repository, Have done changes with my Readme file. And also add my co-author Rashi Goel (https://github.com/rashigoel) on the page showing all the applications
