### ISSUE TITLE
Lost & Survive

### ISSUE THREAD

**Issue by Utshaw** [IEEEmadC/Apps-2017#43]
Team name: Buet_Matrix
Team Members:
Member Name 1: Farhan Tanvir Utshaw 
E-mail: farhan.tanvir.utshaw@gmail.com 
Member Name 2: Waqar Hassan Khan 
E-mail: waqar.hassan866@gmail.com 
Member Name 3: Ahmed Nafis Fuad  
E-mail: 1505113.anf@ugrad.cse.buet.ac.bd 
Repository link: https://github.com/Utshaw/Lost_AND_Survive
APK File: https://github.com/Utshaw/Lost_AND_Survive/blob/master/Lost%20%26%20Survive.apk
Description: Travelers will find this app extremely helpful as this enables them to know about various useful information while travelling to distant places, knowing about current location,  sending messages , getting direction info and torchlight facility . 
License: MIT
Country: Bangladesh

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by Utshaw** [comment]
Thank you for figuring out the mistake . I've added the APK file .
