### ISSUE TITLE
Aerial

### ISSUE THREAD

**Issue by kts-desilva** [IEEEmadC/Apps-2017#46]
Team name : Aerial

App file : https://github.com/kts-desilva/ClassPrep
Description :  ClassPrep is an application for students to be more productive while preparing for classes.
Youtube Video: [https://www.youtube.com/watch?v=xgXZOf1dr8g](url)

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing.

**Comment by kts-desilva** [comment]
Dear Sir,

We are team Aerial and our github issue has been closed but my team members
and country have not added in the README file. Can you please update these
details ?

Country : Sri Lanka
Author : Senuri De Silva, Sanuwani Dayarathna, Manoj Nilanga

We apologize for the inconvenience occurred.

Thank you!

Regards,
Senuri
