### ISSUE TITLE
Surprise World Cards

### ISSUE THREAD

**Issue by DavincisDreamTeam** [IEEEmadC/Apps-2017#5]
his app seeks to promote learning about the world that the little ones are beginning to know. With the help of our printable cards that will contain images of animals and transportation. The image is focused on the screen with the camera of the cell phone, and from here a detailed image through augmented reality will be appreciated along with a brief hearing description that will be available in English and Spanish, allowing to know more about what is unknown for those Users. Surprise World Cards will enable parents to enrich the education of their children at an early age through technology and involve them in the training process in conjunction with school education. The application can be downloaded on any device that has Android operating system and rear camera.

**Comment by SangramChavan** [comment]
Invalid submission
Reason: No files found.
Follow example https://github.com/IEEEmadC/Apps-2017/issues/4

**Comment by DavincisDreamTeam** [comment]
Hello, 

i have a question, I can give them a google drive link, I could not upload my project to github due to file size problems, or what option they can give me

**Comment by SangramChavan** [comment]
That would work! I can update here for you. Just send an email to IEEEmadC@ieee.org

**Comment by DavincisDreamTeam** [comment]
thank you . I send you an email

**Comment by SangramChavan** [comment]
Received and updating in process..
