### ISSUE TITLE
Citiscope

### ISSUE THREAD

**Issue by FatiulHuqSujoy** [IEEEmadC/Apps-2017#56]
Application Name: Citiscope
Team Name: OK
Team Members: Syed Fatiul Huq, Maliha Nawshin Rahman, S M Shakhawat Hossain
Region: 10
Country: Bangladesh

Repository: https://github.com/FatiulHuqSujoy/citiscopeApp

The source code has been sent as a Drive link to  IEEEmadC@ieee.org

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing !
