### ISSUE TITLE
Event Me

### ISSUE THREAD

**Issue by aswin17** [IEEEmadC/Apps-2017#57]
Application Name: Event-Me
Team Name: Coders' Intersection (PicoPalette)
Team Members: Ramkumar B,   Aswin Sundar, Vigneshwaran D. 
College: Anna University.
Country: India.

Repository:  https://github.com/picopalette/EventMe-Submission.git
Android project: https://github.com/picopalette/event-me.git
Youtube Link:  https://youtu.be/JqdBEK0c7gE

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing !

**Comment by realramkumar** [comment]
Hey, is anything missing. Why not ours is listed yet.

**Comment by SangramChavan** [comment]
Check your repo issue !

**Comment by realramkumar** [comment]
Yeah, you asked for LICENSE and I have replied.
