### ISSUE TITLE
Localee

### ISSUE THREAD

**Issue by anjoshigor** [IEEEmadC/Apps-2017#58]
## Team Name

**BRduo**

## Application Name

**Localee**

## Team Members:

Higor Anjos [@anjoshigor](https://github.com/anjoshigor)

Marcos Alves [@alvesmarcos](https://github.com/alvesmarcos)

## Description:

We think that not only technical and academic knowledge is important to individual development as a human being. The culture and the environment in which we are inserted is crucial to make us better and change the world. Due to that and with the power of the music and cultural acts, we want to create a mobile platform for musicians and artists to share their work through free events. With that, locals could attend these events, enjoy local culture, acquire new skills and have awesome experiences. All of that nicely presented in their own hands, in a intuitive and practical way.

## Repository:

https://github.com/anjoshigor/ieeemadc-contest

**Comment by SangramChavan** [comment]
Will check and revert if anything is missing !

**Comment by SangramChavan** [comment]
Nice concept !

**Comment by anjoshigor** [comment]
Thanks, @SangramChavan !
