### ISSUE TITLE
Instruct Me

### ISSUE THREAD

**Issue by EngMahmoudMagdy** [IEEEmadC/Apps-2017#59]
InstructMe 
Shoubra Team, Benha University
is an app to get a contact for an instructor to develop your self and get new skills by offline training, you can search topics and search for the nearest instructor for your place to get his contacts and you can also send messages for him and endorse his skills in this topic. as an instructor you can show your skills by submitting your youtube channel and any of youtube videos that presents your skills and topics that you master.
[Here is the repo](https://github.com/EngMahmoudMagdy/instructmeapp)

the zip file
[InstructMe_code_Mahmoud_Magdy.zip](https://github.com/IEEEmadC/Apps-2017/files/1150844/InstructMe_code_Mahmoud_Magdy.zip)

**Comment by SangramChavan** [comment]
Please create a repo and share the repo link with team name

**Comment by EngMahmoudMagdy** [comment]
done
